#!/bin/bash
# Campus Compass - Pi Edge Node Provisioning Script
# This script configures a fresh Raspberry Pi for production.

set -e

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " Campus Compass ► Edge Node Provisioning"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# 1. Check if run as root
if [ "$EUID" -ne 0 ]; then
  echo "❌ Please run as root (use sudo)"
  exit 1
fi

# 2. Prompts
read -p "Enter BUS_ID (e.g., bus-1): " BUS_ID
read -p "Enter VPS_IP (e.g., 72.61.250.73): " VPS_IP
read -p "Enter CAMERA_IP (e.g., 192.168.1.34): " CAMERA_IP
read -p "Enter CAMERA STREAM RTSP_PATH (e.g., stream1): " CAMERA_RTSP_PATH
read -p "Enter MEDIA_MTX STREAM_PASSWORD: " STREAM_PASSWORD

# Set assumed defaults for everything else
CAMERA_USER="admin"
CAMERA_PASS="admin123"

echo ""
echo "📦 Installing system dependencies..."
apt-get update
apt-get install -y ffmpeg python3-venv python3-pip i2c-tools overlayroot

# Create install dir
INSTALL_DIR="/opt/campus-compass"
mkdir -p "$INSTALL_DIR/pi"
chown -R pi:pi "$INSTALL_DIR"

echo "⚙️ Generating /etc/campus-compass.env..."
cat << EOF > /etc/campus-compass.env
# Generated by init_pi.sh
BUS_ID=$BUS_ID
VPS_IP=$VPS_IP
CAMERA_IP=$CAMERA_IP
CAMERA_USER=$CAMERA_USER
CAMERA_PASS=$CAMERA_PASS
CAMERA_RTSP_PATH=$CAMERA_RTSP_PATH
STREAM_PATH=live_$BUS_ID
RTMP_PASS=$STREAM_PASSWORD
GPS_ENABLED=true
IMU_ENABLED=true
GPS_PORT=/dev/ttyS0
I2C_BUS=1
EOF
chmod 600 /etc/campus-compass.env

echo "🐍 Setting up Python Virtual Environment..."
# Run as pi user
sudo -u pi bash << EOF
cd $INSTALL_DIR
python3 -m venv venv
source venv/bin/activate
pip install pynmea2 pyserial smbus2 firebase-admin
EOF

# Copy codebase
cp -r ./* "$INSTALL_DIR/pi/"
chown -R pi:pi "$INSTALL_DIR/pi"

echo "🔌 Configuring systemd services..."
cp camstream.service /etc/systemd/system/
cp sensor_service.service /etc/systemd/system/

systemctl daemon-reload
systemctl enable camstream.service
systemctl enable sensor_service.service

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " ✅ Provisioning Complete!"
echo ""
echo " Services installed and enabled. To start them now:"
echo "   sudo systemctl start camstream sensor_service"
echo ""
echo " ⚠️ IMPORTANT: For production, enable the read-only file system."
echo "   Edit /etc/overlayroot.conf and set:"
echo "   overlayroot=\"tmpfs\""
echo "   Then reboot."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
