#!/bin/bash
# =============================================================================
# Campus Compass — Portable Pi Edge Node Installer
# =============================================================================
# Supports any fresh Raspberry Pi OS (Bookworm or Bullseye).
# Detects the current user — no hardcoded usernames.
#
# Usage:
#   git clone git@github.com:AnujKushwah15/campus-compass.git
#   cd campus-compass/backend/pi
#   chmod +x setup_pi.sh
#   sudo ./setup_pi.sh
#
# Or one-liner on a Pi with SSH key already configured:
#   curl -sS https://raw.githubusercontent.com/AnujKushwah15/campus-compass/main/backend/pi/setup_pi.sh -o setup_pi.sh && chmod +x setup_pi.sh && sudo ./setup_pi.sh
# =============================================================================

set -e

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BOLD}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " 🚌  Campus Compass — Pi Edge Node Provisioning"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${NC}"

# ─── 1. Root check ────────────────────────────────────────────────────────────
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}❌ Please run as root (use sudo)${NC}"
  exit 1
fi

# ─── 2. Detect actual user (the one who called sudo) ──────────────────────────
PI_USER="${SUDO_USER:-$(logname 2>/dev/null || echo pi)}"
PI_HOME=$(eval echo "~$PI_USER")
REPO_DIR="$PI_HOME/campus-compass"
PI_PI_DIR="$REPO_DIR/backend/pi"
PI_VENV="$PI_PI_DIR/venv"

echo -e "${YELLOW}📋 Detected config:${NC}"
echo "   User:     $PI_USER"
echo "   Home:     $PI_HOME"
echo "   Repo:     $REPO_DIR"
echo "   Pi dir:   $PI_PI_DIR"
echo ""

# ─── 3. Install system packages ───────────────────────────────────────────────
echo "📦 Installing system dependencies..."
apt-get update -qq
apt-get install -y ffmpeg python3-venv python3-pip i2c-tools git curl arp-scan

# ─── 4. Clone or update repo ──────────────────────────────────────────────────
if [ -d "$REPO_DIR/.git" ]; then
  echo "🔄 Repo already cloned — pulling latest..."
  sudo -u "$PI_USER" git -C "$REPO_DIR" pull origin main
else
  echo "📥 Cloning campus-compass repo..."
  sudo -u "$PI_USER" git clone git@github.com:AnujKushwah15/campus-compass.git "$REPO_DIR"
fi

# ─── 5. Gather configuration ──────────────────────────────────────────────────
echo ""
echo -e "${BOLD}⚙️  Bus Configuration${NC}"
echo "(Press Enter to accept defaults where shown)"
echo ""

read -p "  BUS_ID              [e.g. bus-1]: " BUS_ID
BUS_ID="${BUS_ID:-bus-1}"

read -p "  VPS_IP              [72.61.250.73]: " VPS_IP
VPS_IP="${VPS_IP:-72.61.250.73}"

read -p "  CAMERA_IP           [e.g. 192.168.1.34]: " CAMERA_IP
CAMERA_IP="${CAMERA_IP:-192.168.1.34}"

read -p "  CAMERA_USER         [admin]: " CAMERA_USER
CAMERA_USER="${CAMERA_USER:-admin}"

read -s -p "  CAMERA_PASS         (hidden): " CAMERA_PASS
echo ""
CAMERA_PASS="${CAMERA_PASS:-admin123}"

read -p "  CAMERA_RTSP_PATH    [stream1]: " CAMERA_RTSP_PATH
CAMERA_RTSP_PATH="${CAMERA_RTSP_PATH:-stream1}"

read -s -p "  RTMP_PASS (MediaMTX publisher password): " RTMP_PASS
echo ""

# Detect GPS serial port
GPS_PORT="/dev/ttyS0"
for port in /dev/ttyAMA0 /dev/serial0 /dev/ttyS0 /dev/ttyUSB0; do
  if [ -e "$port" ]; then
    GPS_PORT="$port"
    break
  fi
done
echo "  GPS_PORT auto-detected: $GPS_PORT"

echo ""

# ─── 6. Write /etc/campus-compass.env ────────────────────────────────────────
echo "🔐 Writing /etc/campus-compass.env..."
cat > /etc/campus-compass.env <<EOF
# Generated by setup_pi.sh on $(date)
# DO NOT commit this file — it contains secrets.

# Bus identity
BUS_ID=$BUS_ID
VPS_IP=$VPS_IP

# IP Camera
CAMERA_IP=$CAMERA_IP
CAMERA_USER=$CAMERA_USER
CAMERA_PASS=$CAMERA_PASS
CAMERA_RTSP_PATH=$CAMERA_RTSP_PATH

# MediaMTX stream
STREAM_PATH=live_$BUS_ID
RTMP_PASS=$RTMP_PASS

# Sensor config
GPS_ENABLED=true
IMU_ENABLED=true
GPS_PORT=$GPS_PORT
I2C_BUS=1
EOF
chmod 600 /etc/campus-compass.env
echo "   ✅ /etc/campus-compass.env written (chmod 600)"

# ─── 7. Python virtual environment ───────────────────────────────────────────
echo "🐍 Setting up Python virtual environment..."
sudo -u "$PI_USER" python3 -m venv "$PI_VENV"
sudo -u "$PI_USER" "$PI_VENV/bin/pip" install --upgrade pip -q
sudo -u "$PI_USER" "$PI_VENV/bin/pip" install -r "$PI_PI_DIR/requirements.txt" -q
echo "   ✅ venv ready at $PI_VENV"

# ─── 8. Install service files ────────────────────────────────────────────────
echo "🔌 Installing systemd services..."

# Substitute placeholders with real values in service files
for svc in camstream sensor_service; do
  SRC="$PI_PI_DIR/${svc}.service"
  DEST="/etc/systemd/system/${svc}.service"
  sed \
    -e "s|\${PI_USER}|$PI_USER|g" \
    -e "s|\${PI_WORKDIR}|$PI_PI_DIR|g" \
    -e "s|\${PI_VENV}|$PI_VENV|g" \
    "$SRC" > "$DEST"
  echo "   ✅ Installed $DEST"
done

systemctl daemon-reload
systemctl enable camstream.service sensor_service.service
echo "   ✅ Services enabled for auto-start on boot"

# ─── 9. Auto-update cron ──────────────────────────────────────────────────────
echo "⏰ Configuring auto-update cron (every 5 minutes)..."

UPDATE_SCRIPT="$PI_HOME/update_campus_compass.sh"

# Write update script if not present or if it points to wrong branch
cat > "$UPDATE_SCRIPT" <<'SCRIPT'
#!/bin/bash
REPO="$HOME/campus-compass"
cd "$REPO"

BRANCH=$(git rev-parse --abbrev-ref HEAD)
git fetch origin "$BRANCH" --quiet

LOCAL=$(git rev-parse HEAD)
REMOTE=$(git rev-parse "origin/$BRANCH")

if [ "$LOCAL" != "$REMOTE" ]; then
  CHANGES=$(git diff --name-only HEAD "origin/$BRANCH" | grep "^backend/pi/" || true)
  git merge "origin/$BRANCH" --quiet

  if [ -n "$CHANGES" ]; then
    echo "$(date): Changes in backend/pi/ — reinstalling services..."

    # Re-apply sed substitutions from service templates
    PI_USER=$(id -un)
    PI_PI_DIR="$REPO/backend/pi"
    PI_VENV="$PI_PI_DIR/venv"

    for svc in camstream sensor_service; do
      sed \
        -e "s|\${PI_USER}|$PI_USER|g" \
        -e "s|\${PI_WORKDIR}|$PI_PI_DIR|g" \
        -e "s|\${PI_VENV}|$PI_VENV|g" \
        "$PI_PI_DIR/${svc}.service" | sudo tee "/etc/systemd/system/${svc}.service" > /dev/null
    done

    # Update Python deps in case requirements.txt changed
    "$PI_VENV/bin/pip" install -r "$PI_PI_DIR/requirements.txt" -q

    sudo systemctl daemon-reload
    sudo systemctl restart camstream.service sensor_service.service
    echo "$(date): Services restarted."
  else
    echo "$(date): No backend/pi/ changes. Skipping restart."
  fi
else
  echo "$(date): Already up to date."
fi
SCRIPT

chown "$PI_USER:$PI_USER" "$UPDATE_SCRIPT"
chmod +x "$UPDATE_SCRIPT"

# Add cron entry if not already present
CRON_ENTRY="*/5 * * * * $UPDATE_SCRIPT >> $PI_HOME/update_campus_compass.log 2>&1"
(crontab -u "$PI_USER" -l 2>/dev/null | grep -v "update_campus_compass"; echo "$CRON_ENTRY") | crontab -u "$PI_USER" -
echo "   ✅ Cron installed for $PI_USER"

# ─── 10. Start services now ───────────────────────────────────────────────────
echo "▶️  Starting services..."
systemctl start camstream.service sensor_service.service

# ─── 11. Summary ──────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo " ✅  Provisioning Complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${NC}"
echo "  Bus ID:      $BUS_ID"
echo "  VPS:         $VPS_IP"
echo "  Camera:      $CAMERA_IP"
echo "  Stream Path: live_$BUS_ID"
echo ""
echo "  Services:"
echo "    systemctl status camstream.service"
echo "    systemctl status sensor_service.service"
echo ""
echo "  Live logs:"
echo "    journalctl -u camstream -f"
echo "    journalctl -u sensor_service -f"
echo ""
echo "  Auto-update: every 5 min via cron"
echo "    tail -f $PI_HOME/update_campus_compass.log"
echo ""
echo -e "${YELLOW}⚠️  To add a new bus, run this script again on a second Pi${NC}"
echo "   and enter a different BUS_ID (e.g. bus-2)"
echo ""
